---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/books":
    get:
      summary: Retrieves all books, with optional filters for published status and
        pagination
      tags:
      - Books
      parameters:
      - name: published
        in: query
        required: false
        description: Filter by published status
        schema:
          type: boolean
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Number of books per page
        schema:
          type: integer
      responses:
        '200':
          description: "|- books array empty!"
    post:
      summary: Creates a new book
      tags:
      - Books
      parameters: []
      responses:
        '201':
          description: "|- book created"
        '422':
          description: "|- invalid request"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                published_at:
                  type: string
                  format: date
              required:
              - title
              - description
              - published_at
  "/books/search":
    get:
      summary: Searches books by title
      tags:
      - Books
      parameters:
      - name: query
        in: query
        required: true
        description: Search query for book titles
        schema:
          type: string
      responses:
        '200':
          description: "|- books found"
  "/books/published_in_year":
    get:
      summary: Retrieves books published in a specific year
      tags:
      - Books
      parameters:
      - name: year
        in: query
        required: true
        description: Year of publication
        schema:
          type: integer
      responses:
        '200':
          description: "|- books found"
  "/books/{id}":
    get:
      summary: Retrieves a single book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the book to retrieve
        schema:
          type: string
      responses:
        '200':
          description: "|- book found"
        '404':
          description: "|- book not found"
    patch:
      summary: Updates a book with various attributes
      tags:
      - Books
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the book to update
        schema:
          type: string
      responses:
        '200':
          description: "|- book updated"
        '404':
          description: "|- book not found"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                published_at:
                  type: string
                  format: date
                published:
                  type: boolean
              required:
              - title
              - description
              - published_at
    delete:
      summary: Deletes a book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the book to delete
        schema:
          type: string
      responses:
        '204':
          description: "|- book deleted"
        '404':
          description: "|- book not found"
  "/books/{id}/publish":
    patch:
      summary: Publishes a book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the book to publish
        schema:
          type: string
      responses:
        '200':
          description: "|- book published"
        '404':
          description: "|- book not found"
