---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/books":
    get:
      summary: Retrieves books with pagination
      tags:
      - Books
      responses:
        '200':
          description: "|- paginated books"
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Number of books per page
        schema:
          type: integer
    post:
      summary: Creates a book
      tags:
      - Books
      parameters: []
      responses:
        '201':
          description: "|- book created"
        '422':
          description: "|- invalid request"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                published_at:
                  type: string
                  format: date
              required:
              - title
              - description
              - published_at
  "/books/{id}":
    get:
      summary: Retrieves a single book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        description: ID of the book to retrieve
        required: true
        schema:
          type: string
      responses:
        '200':
          description: "|- book found"
        '404':
          description: "|- book not found"
    patch:
      summary: Updates a book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        description: ID of the book to update
        required: true
        schema:
          type: string
      responses:
        '200':
          description: "|- book updated"
        '404':
          description: "|- book not found"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                published_at:
                  type: string
                  format: date
              required:
              - title
              - description
              - published_at
    delete:
      summary: Deletes a book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        description: ID of the book to delete
        required: true
        schema:
          type: string
      responses:
        '204':
          description: "|- book deleted"
        '404':
          description: "|- book not found"
